version: "3.9"
services:
  postgres:
    image: postgres:13
    restart: always
    container_name: integration-tests-prisma
    environment:
      - POSTGRES_USER=prisma
      - POSTGRES_PASSWORD=prisma
      - POSTGRES_DB=tests
    ports:
      - "5433:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
